name: Analyze Faker with SonarCloud

on:
  push:
    branches:
      - master # ou main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze Faker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone Faker Repository
        run: |
          git clone https://github.com/joke2k/faker.git faker_source

      - name: Install dependencies for analysis
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          # Adicione as dependências que os testes do Faker precisam
          # Você pode consultar o pyproject.toml ou setup.cfg do Faker para a lista completa
          pip install freezegun validators # Essas são as que apareceram no erro
          # Algumas outras comuns que o Faker pode precisar para testes:
          pip install r-e2 # Ou outras de "dev" ou "test" do pyproject.toml
          # O jeito mais fácil para dependências de teste é instalar os extras:
          pip install "faker-source[test]" # Tenta instalar o grupo 'test' definido no pyproject.toml

      - name: Run Faker tests and collect coverage
        run: |
          cd faker_source
          pip install -e . # Instala o Faker em modo editável
          # Certifique-se de que os testes sejam encontrados
          coverage run -m pytest tests/

          # Gera o relatório uma pasta acima, na raiz do seu repositório de análise
          coverage xml -o ../coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}