name: Analyze Faker with SonarCloud

on:
  push:
    branches:
      - master # ou main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze Faker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone Faker Repository
        run: |
          git clone https://github.com/joke2k/faker.git faker_source

      - name: Install dependencies for analysis
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install freezegun validators # Mantenha essas, pois são necessárias e funcionaram.
          # REMOVA A LINHA ABAIXO:
          # pip install r-e2 # Esta linha está causando o erro

      - name: Run Faker tests and collect coverage (optional)
        run: |
          cd faker_source
          pip install -e .
          coverage run -m pytest tests/
          coverage xml -o ../coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}